# Generated by Django 4.2 on 2024-12-28 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userApp', '0005_userprofile_email_verified_userprofile_id_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('relationship', models.CharField(max_length=50, verbose_name='关系')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('note', models.TextField(blank=True, max_length=500, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '紧急联系人',
                'verbose_name_plural': '紧急联系人',
                'ordering': ['-created_time'],
            },
        ),
    ]
